### ISSUE TITLE
Create Pickle Object - Solenya

### ISSUE THREAD

**Issue by jakeschurch** [jakeschurch/SEC-Swiss-Army-Knife#7]
Pickling is storing data in a bytestream to access after runtime. My thoughts are that we use pickling to store query logs, saved history, etc. by implementing some sort of pickled queue.

Solenya will extend a saved queries/query history listing (decided deque of filings in lists)

## Query History To-Do:
- [x] Determine n-query size `update: setting default max length as 5`
- [x] Implement deque object

**Comment by jakeschurch** [comment]
Created and implemented into feature branch

**Comment by dlouton** [comment]
Just a question on this one.  I am familiar with pickle and thought that Solenya must be a package built on pickle, but I can't seem to find any references to it.  Can you clarify what Solenya is?  As of a few days ago I didn't see it referenced in the code either, but I will review again.

**Comment by jakeschurch** [comment]
@dlouton My apologies - its a reference to the Adult Swim show Rick and Morty. Solenya is just the name of the class I created to pickle filings... In the show, it means "pickle man"

**Comment by dlouton** [comment]
Ahhh....  Thanks for clarifying.  I am familiar with some of the earlier shows from Adult Swim, but this one is new to me.  Anyway, makes perfect sense.  I will go over that block of code again.
